var dict = {
    en: {
        'SITE-TITLE':'Engaged in the development of sites on cms WordPress',
        'Purpose':'Purpose:',
        'Purse-Text':'Getting a position of a web developer.',
        'Professional-Skills':'Professional skills:',
        'Experience':'Experience:',
        'Experience-Content':'html coder, February 2017 - February 2018.',
        'Experience-Content-two':'web developer, February 2018 - December 2019.',
        'Experience-Content-three':'web-developer, October 2020 - present.',
        'Experience-Content-four':'wordpress developer, June 2022 - present.',
        'Functional-Responsibilities':'Functional responsibilities:',
        'Responsibilities-Text1':'Development and implementation of new features and capabilities.',
		'Responsibilities-Text2':'Creation and maintenance of site architecture.',
        'Responsibilities-Text3':'Providing technical aspects of the CMS.',
		'Responsibilities-Text4':'Responsive design and transformation into a working theme and plugin.',
        'Responsibilities-Text5':'Cutting/layout files in HTML, CSS, JS.',
        'Responsibilities-Text6':'Creating New WordPress Themes From Scratch.',
        'Responsibilities-Text7':'Debugging and improving existing WordPress sites.',
        'Responsibilities-Text8':'Optimizing Websites for Page Speed ​​and Load Speed.',
        'Responsibilities-Text9':'Transfer, placement of the site on the hosting.',
        'Work-Html':'Coding "HTML":',
        'Work-Examples':'Work-Examples:',
        'Themes-WordPress':'Themes "WordPress":',
        'Applications-React':'"React" Application:',
        'Education':'Education:',
        'Education-One':'National Metallurgical Academy of Ukraine, Dnipro',
        'Education-Two':'Industrial College of Ukraine, Dnipro.',
        // 'Personal-Qualities':'Personal qualities:',
        'Qualities-Text':'Attentiveness, responsibility, technical thinking, poise, concentration, high degree of self- organization, discipline, focus on achieving results.',
        'HEADING-ONE':'About me:',
        'SOME-TEXT':'Some text in tag P',
        'ANOTHER-TEXT':'another text1',
        'First-Name':'Vitaliy',
        'Last-Name':'Nosov',
        'Write-Me':'Write Me',
        'Location':'Location:',
        'A-Country':'Ukraine',
        'City':'Kiev',
        'Contact':'Contact:',
        'Social- Network':'Social network:',
        'languages':'Languages:',
        'English':'English',
        'Ru':'Rusian',
        'Uk':'Ukranian',
        'Download':'Download PDF:',
        'Email-Button':'Send',
        'Attach-File':'Attach file...'



    },
    uk: {
        'SITE-TITLE':'Займаюся розробкою веб-сайтів на cms WordPress',
        'Purpose':'Мета:',
        'Purse-Text':'Отримання посади веб-розробника.',
        'Professional-Skills':'Професійні навички:',
        'Experience':'Досвід роботи:',
        'Experience-Content':'html coder, лютий 2017 - лютий 2018.',
        'Experience-Content-two':'web-developer, лютий 2018 - грудень 2019.',
        'Experience-Content-three':'web-developer, Жовтень 2020 - теперішній час.',
        'Experience-Content-four':'wordpress-developer, червень 2022 - теперішній час.',
        "Functional-Responsibilities": "Обов'язки:",
        'Responsibilities-Text1':'Розробка та впровадження нових функцій і можливостей.',
        'Responsibilities-Text2':'Створення та супровід архітектури веб-сайту.',
		'Responsibilities-Text3':'Забезпечення технічними аспектами CMS.',
		'Responsibilities-Text4':'Адаптивний дизайн і перетворення на робочу тему та плагін.',
        'Responsibilities-Text5':'Нарізка/верстка дизайнів файлів у HTML, CSS, JS.',
        'Responsibilities-Text6':'Створення нових тем WordPress з нуля.',
        'Responsibilities-Text7':'Налагодження та поліпшення наявних сайтів WordPress.',
        'Responsibilities-Text8':'Оптимізація веб-сайтів для швидкості сторінки та завантаження.',
        'Responsibilities-Text9':'Перенесення, розгортання веб-сайту на хостингу.',
        'Work-Examples':'Приклади робіт:',
        'Work-Html':'Верстка «HTML»:',
        'Themes-WordPress':'Теми на «WordPress»:',
        'Applications-React':'Додаток на «React»:',
        'Education':'Освіта:',
        'Education-One':'Національна металургійна академія України, Дніпро.',
        'Education-Two':'Індустріальний коледж України, Дніпро.',
        // 'Personal-Qualities': 'Личные качества:',
        'Qualities-Text':'Уважність, відповідальність, технічне мислення, зосередженість, високий ступінь самоорганізації, дисциплінованість, орієнтованість на досягнення результату.',
        'HEADING-ONE':'Про мене:',
        'SOME-TEXT':'Some text in tag P',
        'ANOTHER-TEXT':'another text1',
        'First-Name':'Віталій',
        'Last-Name':'Носов',
        'Write-Me':'Написати Мені',
        'Location':'Місцезнаходження:',
        'A-Country':'Україна',
        'City':'Київ',
        'Contact':'Контакти:',
        'Social- Network':'Соціальні мережі:',
        'languages':'Мови:',
        'English':'Англійська',
        'Ru':'Російська',
        'Uk':'Українська',
        'Download':'Завантажити PDF:',
        'Email-Button':'Відправити',
        'Attach-File':'Прикріпити файл...'
    }
};