var dict = {
    en: {
        'SITE-TITLE':'Engaged in the development of sites on',
        'Purpose':'Purpose:',
        'Purse-Text':'Getting a position of a web developer.',
        'Professional-Skills':'Professional skills:',
        'Experience':'Experience:',
        'Experience-Content':'html coder, February 2017 - February 2018.',
        'Experience-Content-two':'web developer, February 2018 - December 2019.',
        'Experience-Content-three':'web-developer, October 2020 - present.',
        'Experience-Content-four':'wordpress developer, June 2022 - present.',
        'Functional-Responsibilities':'Functional responsibilities:',
        'Responsibilities-Text1':'Development and implementation of new features and capabilities.',
		'Responsibilities-Text2':'Creation and maintenance of site architecture.',
        'Responsibilities-Text3':'Providing technical aspects of the CMS.',
		'Responsibilities-Text4':'Responsive design and transformation into a working theme and plugin.',
        'Responsibilities-Text5':'Cutting/layout files in HTML, CSS, JS.',
        'Responsibilities-Text6':'Creating New WordPress Themes From Scratch.',
        'Responsibilities-Text7':'Debugging and improving existing WordPress sites.',
        'Responsibilities-Text8':'Optimizing Websites for Page Speed ​​and Load Speed.',
        'Responsibilities-Text9':'Transfer, placement of the site on the hosting.',
        'Work-Html':'Coding "HTML":',
        'Work-Examples':'Work-Examples:',
        'Themes-WordPress':'Themes "WordPress":',
        'Applications-React':'"React" Application:',
        'Education':'Education:',
        'Education-One':'National Metallurgical Academy of Ukraine, Dnipro',
        'Education-Two':'Industrial College of Ukraine, Dnipro.',
        // 'Personal-Qualities':'Personal qualities:',
        'Qualities-Text':'Attentiveness, responsibility, technical thinking, poise, concentration, high degree of self- organization, discipline, focus on achieving results.',
        'HEADING-ONE':'About me:',
        'SOME-TEXT':'Some text in tag P',
        'ANOTHER-TEXT':'another text1',
        'First-Name':'Vitaliy',
        'Last-Name':'Nosov',
        'Write-Me':'Write Me',
        'Location':'Location:',
        'A-Country':'Ukraine',
        'City':'Dnepr',
        'Contact':'Contact:',
        'Social- Network':'Social network:',
        'languages':'Languages:',
        'English':'English',
        'Ru':'Rusian',
        'Ukr':'Ukranian',
        'Download':'Download:',
        'Email-Button':'Send',
        'Attach-File':'Attach file...'



    },
    ru: {
        'SITE-TITLE':'Занимаюсь разработкой веб-сайтов на',
        'Purpose':'Цель:',
        'Purse-Text':'Получение должности веб-разработчика.',
        'Professional-Skills':'Профессиональные навыки:',
        'Experience':'Опыт работы:',
        'Experience-Content':'html coder, Февраль 2017 – Февраль 2018.',
        'Experience-Content-two':'web-developer, Февраль 2018 – Декабрь 2019.',
        'Experience-Content-three':'web-developer, Октябрь 2020 – настоящее время.',
        'Experience-Content-four':'wordpress-developer, Июнь 2022 – настоящее время.',
        'Functional-Responsibilities':'Обязанности:',
        'Responsibilities-Text1':'Разработка и внедрение новых функций и возможностей.',
        'Responsibilities-Text2':'Создание и сопровождение архитектуры веб-сайта.',
		'Responsibilities-Text3':'Обеспечение техническими аспектами CMS.',
		'Responsibilities-Text4':'Адаптивный дизайн и превращение в рабочую тему и плагин.',
        'Responsibilities-Text5':'Нарезка/верстка дизайнов файлов в HTML, CSS, JS.',
        'Responsibilities-Text6':'Создание новых тем WordPress с нуля.',
        'Responsibilities-Text7':'Отладка и улучшение существующих сайтов WordPress.',
        'Responsibilities-Text8':'Оптимизация веб-сайтов для скорости страницы и загрузки.',
        'Responsibilities-Text9':'Перенос, развертывание веб-сайта на хостинге.',
        'Work-Examples':'Примеры работ:',
        'Work-Html':'Верстка "HTML":',
        'Themes-WordPress':'Темы на "WordPress":',
        'Applications-React':'Приложение на "React":',
        'Education':'Образование:',
        'Education-One':'Национальная металлургическая академия Украины, Днепр.',
        'Education-Two':'Индустриальный коледж Украины, Днепр.',
        // 'Personal-Qualities': 'Личные качества:',
        'Qualities-Text':'Внимательность, ответственность, техническое мышление, сосредоточенность, высокая степень самоорганизации, дисциплинированность, ориентированность на достижение результата.',
        'HEADING-ONE':'Обо мне:',
        'SOME-TEXT':'Some text in tag P',
        'ANOTHER-TEXT':'another text1',
        'First-Name':'Виталий',
        'Last-Name':'Носов',
        'Write-Me':'Написать Мне',
        'Location':'Местоположение:',
        'A-Country':'Украина',
        'City':'Днепр',
        'Contact':'Контакты:',
        'Social- Network':'Социальные сети:',
        'languages':'Языки:',
        'English':'Английский',
        'Ru':'Русский',
        'Ukr':'Украинский',
        'Download':'Скачать:',
        'Email-Button':'Отправить',
        'Attach-File':'Прикрепить файл...'
    }
};